import { useEffect } from "react";
import { addSongsListToDatabase } from "@/services/spotifyDatabaseService";

// 100+ unique songs (English & Hindi), not in your provided exclusion list
const SONGS = [
  // --- English Songs ---
  { name: "Chasing Cars", artist: "Snow Patrol", category: "Relaxed", language: "English" },
  { name: "Demons", artist: "Imagine Dragons", category: "Energetic", language: "English" },
  { name: "Somebody That I Used To Know", artist: "Gotye", category: "Calm", language: "English" },
  { name: "Counting Blue Cars", artist: "Dishwalla", category: "Calm", language: "English" },
  { name: "Say You Won't Let Go", artist: "James Arthur", category: "Romantic", language: "English" },
  { name: "Let Me Down Slowly", artist: "Alec Benjamin", category: "Moderate", language: "English" },
  { name: "Believer", artist: "Imagine Dragons", category: "Energetic", language: "English" },
  { name: "Love Story", artist: "Taylor Swift", category: "Romantic", language: "English" },
  { name: "Heathens", artist: "Twenty One Pilots", category: "Moody", language: "English" },
  { name: "Take Me To Church", artist: "Hozier", category: "Moody", language: "English" },
  { name: "Hey There Delilah", artist: "Plain White T's", category: "Calm", language: "English" },
  { name: "Lovely", artist: "Billie Eilish & Khalid", category: "Calm", language: "English" },
  { name: "Happier", artist: "Ed Sheeran", category: "Sad", language: "English" },
  { name: "Memories", artist: "Maroon 5", category: "Mellow", language: "English" },
  { name: "Shape of You", artist: "Ed Sheeran", category: "Upbeat", language: "English" },
  { name: "Radioactive", artist: "Imagine Dragons", category: "Energetic", language: "English" },
  { name: "Counting Blue Cars", artist: "Dishwalla", category: "Calm", language: "English" },
  { name: "Paradise", artist: "Coldplay", category: "Chill", language: "English" },
  { name: "Viva La Vida", artist: "Coldplay", category: "Energetic", language: "English" },
  { name: "Stressed Out", artist: "Twenty One Pilots", category: "Chill", language: "English" },
  { name: "Girls Like You", artist: "Maroon 5", category: "Upbeat", language: "English" },
  { name: "Bad Guy", artist: "Billie Eilish", category: "Energetic", language: "English" },
  { name: "Senorita", artist: "Shawn Mendes, Camila Cabello", category: "Romantic", language: "English" },
  { name: "Cheap Thrills", artist: "Sia", category: "Upbeat", language: "English" },
  { name: "Hymn For The Weekend", artist: "Coldplay", category: "Energetic", language: "English" },
  { name: "Adventure of a Lifetime", artist: "Coldplay", category: "Upbeat", language: "English" },
  { name: "Sugar", artist: "Maroon 5", category: "Upbeat", language: "English" },
  { name: "Rather Be", artist: "Clean Bandit", category: "Upbeat", language: "English" },
  { name: "Love Me Like You Do", artist: "Ellie Goulding", category: "Romantic", language: "English" },
  { name: "Wake Me Up", artist: "Avicii", category: "Energetic", language: "English" },
  { name: "On My Way", artist: "Alan Walker", category: "Upbeat", language: "English" },
  { name: "Alone", artist: "Alan Walker", category: "Chill", language: "English" },
  { name: "Attention", artist: "Charlie Puth", category: "Moderate", language: "English" },
  { name: "We Don't Talk Anymore", artist: "Charlie Puth", category: "Chill", language: "English" },
  { name: "Faded", artist: "Alan Walker", category: "Moody", language: "English" },
  { name: "Rockabye", artist: "Clean Bandit", category: "Upbeat", language: "English" },
  { name: "Happier", artist: "Marshmello, Bastille", category: "Sad", language: "English" },
  { name: "Animals", artist: "Martin Garrix", category: "Energetic", language: "English" },
  { name: "Stitches", artist: "Shawn Mendes", category: "Romantic", language: "English" },
  { name: "7 Years", artist: "Lukas Graham", category: "Mellow", language: "English" },
  { name: "Counting Stars", artist: "OneRepublic", category: "Upbeat", language: "English" },
  { name: "See You Again", artist: "Wiz Khalifa", category: "Sad", language: "English" },
  { name: "Treat You Better", artist: "Shawn Mendes", category: "Romantic", language: "English" },
  { name: "Love Yourself", artist: "Justin Bieber", category: "Chill", language: "English" },
  { name: "Let Me Love You", artist: "DJ Snake, Justin Bieber", category: "Romantic", language: "English" },
  { name: "Don't Let Me Down", artist: "The Chainsmokers", category: "Moody", language: "English" },
  { name: "Closer", artist: "The Chainsmokers, Halsey", category: "Upbeat", language: "English" },
  { name: "Something Just Like This", artist: "The Chainsmokers, Coldplay", category: "Upbeat", language: "English" },
  { name: "Takeaway", artist: "The Chainsmokers, Illenium", category: "Moderate", language: "English" },
  { name: "Sunflower", artist: "Post Malone, Swae Lee", category: "Chill", language: "English" },
  { name: "Without Me", artist: "Halsey", category: "Moody", language: "English" },
  { name: "Bad Liar", artist: "Imagine Dragons", category: "Moody", language: "English" },
  { name: "If I Can't Have You", artist: "Shawn Mendes", category: "Upbeat", language: "English" },
  { name: "Youngblood", artist: "5 Seconds of Summer", category: "Energetic", language: "English" },
  { name: "Don't Start Now", artist: "Dua Lipa", category: "Upbeat", language: "English" },
  { name: "Memories", artist: "Shawn Mendes", category: "Mellow", language: "English" },
  { name: "Break My Heart", artist: "Dua Lipa", category: "Moody", language: "English" },
  { name: "Intentions", artist: "Justin Bieber", category: "Upbeat", language: "English" },
  { name: "Before You Go", artist: "Lewis Capaldi", category: "Sad", language: "English" },
  { name: "Physical", artist: "Dua Lipa", category: "Energetic", language: "English" },
  { name: "Watermelon Sugar", artist: "Harry Styles", category: "Upbeat", language: "English" },
  { name: "Toosie Slide", artist: "Drake", category: "Chill", language: "English" },
  { name: "Intentions", artist: "Justin Bieber", category: "Upbeat", language: "English" },
  { name: "Goosebumps", artist: "Travis Scott", category: "Energetic", language: "English" },
  { name: "Circles", artist: "Post Malone", category: "Mellow", language: "English" },
  { name: "Ride", artist: "Twenty One Pilots", category: "Chill", language: "English" },
  { name: "Eastside", artist: "Benny Blanco, Halsey, Khalid", category: "Chill", language: "English" },
  { name: "Beautiful People", artist: "Ed Sheeran, Khalid", category: "Upbeat", language: "English" },
  { name: "Old Town Road", artist: "Lil Nas X", category: "Upbeat", language: "English" },
  { name: "Dance Monkey", artist: "Tones and I", category: "Energetic", language: "English" },
  { name: "Goodbyes", artist: "Post Malone", category: "Sad", language: "English" },
  { name: "Sucker", artist: "Jonas Brothers", category: "Upbeat", language: "English" },
  { name: "Lover", artist: "Taylor Swift", category: "Romantic", language: "English" },
  { name: "Someone You Loved", artist: "Lewis Capaldi", category: "Sad", language: "English" },
  { name: "Don't Call Me Up", artist: "Mabel", category: "Energetic", language: "English" },
  { name: "Uptown Funk", artist: "Mark Ronson, Bruno Mars", category: "Upbeat", language: "English" },
  { name: "Sorry", artist: "Justin Bieber", category: "Upbeat", language: "English" },

  // --- Hindi Songs ---
  { name: "Bekhayali", artist: "Sachet Tandon", category: "Sad", language: "Hindi" },
  { name: "Shayad", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Ghungroo", artist: "Arijit Singh, Shilpa Rao", category: "Upbeat", language: "Hindi" },
  { name: "Pal", artist: "Arijit Singh, Shreya Ghoshal", category: "Romantic", language: "Hindi" },
  { name: "Dil Diyan Gallan", artist: "Atif Aslam", category: "Romantic", language: "Hindi" },
  { name: "Tareefan", artist: "Badshah", category: "Upbeat", language: "Hindi" },
  { name: "Kamariya", artist: "Lijo George, DJ Chetas", category: "Upbeat", language: "Hindi" },
  { name: "Morni Banke", artist: "Guru Randhawa, Neha Kakkar", category: "Upbeat", language: "Hindi" },
  { name: "Laal Ghaghra", artist: "Manj Musik, Herbie Sahara", category: "Upbeat", language: "Hindi" },
  { name: "Proper Patola", artist: "Diljit Dosanjh, Badshah", category: "Upbeat", language: "Hindi" },
  { name: "Tareefan", artist: "Badshah", category: "Upbeat", language: "Hindi" },
  { name: "Akh Lad Jaave", artist: "Badshah, Jubin Nautiyal", category: "Upbeat", language: "Hindi" },
  { name: "Dilbar", artist: "Neha Kakkar, Dhvani Bhanushali", category: "Upbeat", language: "Hindi" },
  { name: "Aankh Marey", artist: "Neha Kakkar, Mika Singh", category: "Upbeat", language: "Hindi" },
  { name: "Bom Diggy Diggy", artist: "Zack Knight, Jasmin Walia", category: "Upbeat", language: "Hindi" },
  { name: "Kala Chashma", artist: "Amar Arshi, Badshah", category: "Upbeat", language: "Hindi" },
  { name: "Suit Suit", artist: "Guru Randhawa, Arjun", category: "Upbeat", language: "Hindi" },
  { name: "Patola", artist: "Guru Randhawa", category: "Upbeat", language: "Hindi" },
  { name: "Ban Ja Rani", artist: "Guru Randhawa", category: "Romantic", language: "Hindi" },
  { name: "High Rated Gabru", artist: "Guru Randhawa", category: "Energetic", language: "Hindi" },
  { name: "Lambiyaan Si Judaiyaan", artist: "Arijit Singh", category: "Sad", language: "Hindi" },
  { name: "Raatan Lambiyan", artist: "Jubin Nautiyal, Asees Kaur", category: "Romantic", language: "Hindi" },
  { name: "Tujhe Kitna Chahne Lage", artist: "Arijit Singh", category: "Sad", language: "Hindi" },
  { name: "Chogada", artist: "Darshan Raval", category: "Upbeat", language: "Hindi" },
  { name: "Kamariya", artist: "Stree", category: "Upbeat", language: "Hindi" },
  { name: "Nashe Si Chadh Gayi", artist: "Arijit Singh", category: "Upbeat", language: "Hindi" },
  { name: "Sau Aasmaan", artist: "Armaan Malik, Neeti Mohan", category: "Chill", language: "Hindi" },
  { name: "Kar Gayi Chull", artist: "Badshah, Fazilpuria", category: "Upbeat", language: "Hindi" },
  { name: "Zaalima", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Hawayein", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Tera Yaar Hoon Main", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Tu Hi Hai", artist: "Rahul Mishra", category: "Romantic", language: "Hindi" },
  { name: "Tu Chale", artist: "Arijit Singh, Shreya Ghoshal", category: "Romantic", language: "Hindi" },
  { name: "Sun Saathiya", artist: "Priya Saraiya, Divya Kumar", category: "Romantic", language: "Hindi" },
  { name: "Jeene Ke Hain Chaar Din", artist: "Sonu Nigam", category: "Upbeat", language: "Hindi" },
  { name: "Galliyan", artist: "Ankit Tiwari", category: "Romantic", language: "Hindi" },
  { name: "Tum Hi Ho Bandhu", artist: "Neeraj Shridhar, Kavita Seth", category: "Upbeat", language: "Hindi" },
  { name: "Jab Tak", artist: "Armaan Malik", category: "Romantic", language: "Hindi" },
  { name: "Raabta", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Enna Sona", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Hasi Ban Gaye", artist: "Ami Mishra", category: "Romantic", language: "Hindi" },
  { name: "Muskurane", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Khairiyat", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Qaafirana", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Tera Hone Laga Hoon", artist: "Atif Aslam", category: "Romantic", language: "Hindi" },
  { name: "Saudagar Sauda Kar", artist: "Anuradha Paudwal, Udit Narayan", category: "Romantic", language: "Hindi" },
  { name: "Saudagar Sauda Kar", artist: "Anuradha Paudwal, Udit Narayan", category: "Romantic", language: "Hindi" },
  { name: "Pee Loon", artist: "Mohit Chauhan", category: "Romantic", language: "Hindi" },
  { name: "Sun Raha Hai Na Tu", artist: "Ankit Tiwari", category: "Sad", language: "Hindi" },
  { name: "Sanam Re", artist: "Arijit Singh", category: "Sad", language: "Hindi" },
  { name: "Tera Ban Jaunga", artist: "Akhil Sachdeva", category: "Romantic", language: "Hindi" },
  { name: "Tum Mile", artist: "Neeraj Shridhar", category: "Romantic", language: "Hindi" },
  { name: "Tu Chale", artist: "Arijit Singh, Shreya Ghoshal", category: "Romantic", language: "Hindi" },
  { name: "Baarish", artist: "Ash King, Shashaa Tirupati", category: "Romantic", language: "Hindi" },
  { name: "Jeene Laga Hoon", artist: "Atif Aslam, Shreya Ghoshal", category: "Romantic", language: "Hindi" }
];

export default function SeedSongs() {
  useEffect(() => {
    async function seedSongs() {
      try {
        await addSongsListToDatabase(SONGS);
        alert("Seeding complete! Similar songs are auto-generated for each song.");
      } catch (e) {
        alert("Seeding failed, see console.");
        console.error(e);
      }
    }
    seedSongs();
  }, []);

  return <div>Seeding songs... Check your console for the result.</div>;
}
