import { useEffect } from "react";
import { addSongsListToDatabase } from "@/services/spotifyDatabaseService";

// 200 unique, original (no remix/unplugged), non-repeated English & Hindi songs for 200-400 range
const SONGS = [
  // ---- English Songs ----
  { name: "Drive", artist: "Incubus", category: "Chill", language: "English" },
  { name: "Iris", artist: "Goo Goo Dolls", category: "Romantic", language: "English" },
  { name: "Wonderwall", artist: "Oasis", category: "Classic", language: "English" },
  { name: "Champagne Supernova", artist: "Oasis", category: "Dreamy", language: "English" },
  { name: "Don't Look Back In Anger", artist: "Oasis", category: "Epic", language: "English" },
  { name: "Bittersweet Symphony", artist: "The Verve", category: "Epic", language: "English" },
  { name: "Unwell", artist: "Matchbox Twenty", category: "Mellow", language: "English" },
  { name: "3AM", artist: "Matchbox Twenty", category: "Mellow", language: "English" },
  { name: "Push", artist: "Matchbox Twenty", category: "Energetic", language: "English" },
  { name: "How to Save a Life", artist: "The Fray", category: "Sad", language: "English" },
  { name: "Over My Head", artist: "The Fray", category: "Emotional", language: "English" },
  { name: "You Found Me", artist: "The Fray", category: "Moody", language: "English" },
  { name: "Boston", artist: "Augustana", category: "Sad", language: "English" },
  { name: "Drops of Jupiter", artist: "Train", category: "Epic", language: "English" },
  { name: "Hey, Soul Sister", artist: "Train", category: "Upbeat", language: "English" },
  { name: "Calling All Angels", artist: "Train", category: "Motivational", language: "English" },
  { name: "Meet Virginia", artist: "Train", category: "Chill", language: "English" },
  { name: "If It's Love", artist: "Train", category: "Romantic", language: "English" },
  { name: "Stolen", artist: "Dashboard Confessional", category: "Romantic", language: "English" },
  { name: "Vindicated", artist: "Dashboard Confessional", category: "Energetic", language: "English" },
  { name: "Hands Down", artist: "Dashboard Confessional", category: "Upbeat", language: "English" },
  { name: "Hanging By A Moment", artist: "Lifehouse", category: "Romantic", language: "English" },
  { name: "You and Me", artist: "Lifehouse", category: "Romantic", language: "English" },
  { name: "Broken", artist: "Lifehouse", category: "Sad", language: "English" },
  { name: "Everything", artist: "Lifehouse", category: "Emotional", language: "English" },
  { name: "Whatever It Takes", artist: "Lifehouse", category: "Motivational", language: "English" },
  { name: "Here Without You", artist: "3 Doors Down", category: "Sad", language: "English" },
  { name: "Kryptonite", artist: "3 Doors Down", category: "Energetic", language: "English" },
  { name: "When I'm Gone", artist: "3 Doors Down", category: "Emotional", language: "English" },
  { name: "Be Like That", artist: "3 Doors Down", category: "Dreamy", language: "English" },
  { name: "Photograph", artist: "Nickelback", category: "Nostalgic", language: "English" },
  { name: "How You Remind Me", artist: "Nickelback", category: "Energetic", language: "English" },
  { name: "Far Away", artist: "Nickelback", category: "Romantic", language: "English" },
  { name: "Someday", artist: "Nickelback", category: "Emotional", language: "English" },
  { name: "Savin' Me", artist: "Nickelback", category: "Sad", language: "English" },
  { name: "If Everyone Cared", artist: "Nickelback", category: "Inspirational", language: "English" },
  { name: "Hero", artist: "Chad Kroeger, Josey Scott", category: "Epic", language: "English" },
  { name: "Follow You Down", artist: "Gin Blossoms", category: "Romantic", language: "English" },
  { name: "Hey Jealousy", artist: "Gin Blossoms", category: "Classic", language: "English" },
  { name: "Found Out About You", artist: "Gin Blossoms", category: "Emotional", language: "English" },
  { name: "I Don't Want to Be", artist: "Gavin DeGraw", category: "Motivational", language: "English" },
  { name: "Not Over You", artist: "Gavin DeGraw", category: "Sad", language: "English" },
  { name: "Chariot", artist: "Gavin DeGraw", category: "Upbeat", language: "English" },
  { name: "Best I Ever Had", artist: "Vertical Horizon", category: "Romantic", language: "English" },
  { name: "Everything You Want", artist: "Vertical Horizon", category: "Classic", language: "English" },
  { name: "You're a God", artist: "Vertical Horizon", category: "Moody", language: "English" },
  { name: "Absolutely (Story of a Girl)", artist: "Nine Days", category: "Upbeat", language: "English" },
  { name: "She Will Be Loved", artist: "Maroon 5", category: "Romantic", language: "English" },
  { name: "This Love", artist: "Maroon 5", category: "Upbeat", language: "English" },
  { name: "Sunday Morning", artist: "Maroon 5", category: "Chill", language: "English" },
  { name: "Unwritten", artist: "Natasha Bedingfield", category: "Motivational", language: "English" },
  { name: "Pocketful of Sunshine", artist: "Natasha Bedingfield", category: "Happy", language: "English" },
  { name: "Love Song", artist: "Sara Bareilles", category: "Upbeat", language: "English" },
  { name: "Brave", artist: "Sara Bareilles", category: "Motivational", language: "English" },
  { name: "Gravity", artist: "Sara Bareilles", category: "Sad", language: "English" },
  { name: "100 Years", artist: "Five for Fighting", category: "Nostalgic", language: "English" },
  { name: "Superman (It's Not Easy)", artist: "Five for Fighting", category: "Emotional", language: "English" },
  { name: "Chasing Pavements", artist: "Adele", category: "Sad", language: "English" },
  { name: "Rumour Has It", artist: "Adele", category: "Energetic", language: "English" },
  { name: "Turning Tables", artist: "Adele", category: "Sad", language: "English" },
  { name: "Set Fire to the Rain", artist: "Adele", category: "Epic", language: "English" },
  { name: "Firework", artist: "Katy Perry", category: "Motivational", language: "English" },
  { name: "Teenage Dream", artist: "Katy Perry", category: "Romantic", language: "English" },
  { name: "Roar", artist: "Katy Perry", category: "Motivational", language: "English" },
  { name: "Hot N Cold", artist: "Katy Perry", category: "Energetic", language: "English" },
  { name: "California Gurls", artist: "Katy Perry, Snoop Dogg", category: "Fun", language: "English" },
  { name: "Last Friday Night", artist: "Katy Perry", category: "Upbeat", language: "English" },
  { name: "Just Give Me a Reason", artist: "P!nk, Nate Ruess", category: "Emotional", language: "English" },
  { name: "Raise Your Glass", artist: "P!nk", category: "Upbeat", language: "English" },
  { name: "F**kin' Perfect", artist: "P!nk", category: "Motivational", language: "English" },
  { name: "So What", artist: "P!nk", category: "Energetic", language: "English" },
  { name: "Try", artist: "P!nk", category: "Motivational", language: "English" },
  { name: "Just the Way You Are", artist: "Bruno Mars", category: "Romantic", language: "English" },
  { name: "Grenade", artist: "Bruno Mars", category: "Sad", language: "English" },
  { name: "Locked Out of Heaven", artist: "Bruno Mars", category: "Energetic", language: "English" },
  { name: "When I Was Your Man", artist: "Bruno Mars", category: "Sad", language: "English" },
  { name: "Young Girls", artist: "Bruno Mars", category: "Mellow", language: "English" },
  { name: "Treasure", artist: "Bruno Mars", category: "Upbeat", language: "English" },
  { name: "It Will Rain", artist: "Bruno Mars", category: "Sad", language: "English" },
  { name: "Talking to the Moon", artist: "Bruno Mars", category: "Dreamy", language: "English" },
  { name: "Somebody to You", artist: "The Vamps, Demi Lovato", category: "Upbeat", language: "English" },
  { name: "Can We Dance", artist: "The Vamps", category: "Fun", language: "English" },
  { name: "Wake Me Up", artist: "Avicii", category: "Motivational", language: "English" },
  { name: "The Nights", artist: "Avicii", category: "Epic", language: "English" },
  { name: "Hey Brother", artist: "Avicii", category: "Upbeat", language: "English" },
  { name: "Waiting For Love", artist: "Avicii", category: "Romantic", language: "English" },
  { name: "Levels", artist: "Avicii", category: "Energetic", language: "English" },
  { name: "Don't You Worry Child", artist: "Swedish House Mafia", category: "Epic", language: "English" },
  { name: "Save the World", artist: "Swedish House Mafia", category: "Motivational", language: "English" },
  { name: "Greyhound", artist: "Swedish House Mafia", category: "Energetic", language: "English" },
  { name: "Titanium", artist: "David Guetta, Sia", category: "Motivational", language: "English" },
  { name: "She Wolf", artist: "David Guetta, Sia", category: "Energetic", language: "English" },
  { name: "Play Hard", artist: "David Guetta, Ne-Yo, Akon", category: "Energetic", language: "English" },
  { name: "Without You", artist: "David Guetta, Usher", category: "Romantic", language: "English" },
  { name: "Dangerous", artist: "David Guetta, Sam Martin", category: "Moody", language: "English" },
  { name: "Turn Me On", artist: "David Guetta, Nicki Minaj", category: "Energetic", language: "English" },

  // ---- Hindi Songs ----
  { name: "Makhna", artist: "Tanishk Bagchi, Yasser Desai", category: "Upbeat", language: "Hindi" },
  { name: "Dil Diyan Gallan", artist: "Atif Aslam", category: "Romantic", language: "Hindi" },
  { name: "Tareefan", artist: "Badshah", category: "Upbeat", language: "Hindi" },
  { name: "Proper Patola", artist: "Diljit Dosanjh, Badshah", category: "Upbeat", language: "Hindi" },
  { name: "Morni Banke", artist: "Guru Randhawa, Neha Kakkar", category: "Upbeat", language: "Hindi" },
  { name: "Laung Laachi", artist: "Mannat Noor", category: "Romantic", language: "Hindi" },
  { name: "Lambiyaan Si Judaiyaan", artist: "Arijit Singh", category: "Sad", language: "Hindi" },
  { name: "Patola", artist: "Guru Randhawa", category: "Upbeat", language: "Hindi" },
  { name: "High Rated Gabru", artist: "Guru Randhawa", category: "Upbeat", language: "Hindi" },
  { name: "Suit Suit", artist: "Guru Randhawa, Arjun", category: "Upbeat", language: "Hindi" },
  { name: "Ban Ja Rani", artist: "Guru Randhawa", category: "Romantic", language: "Hindi" },
  { name: "Akh Lad Jaave", artist: "Badshah, Jubin Nautiyal", category: "Upbeat", language: "Hindi" },
  { name: "Dilbar", artist: "Neha Kakkar, Dhvani Bhanushali", category: "Upbeat", language: "Hindi" },
  { name: "Bom Diggy", artist: "Zack Knight, Jasmin Walia", category: "Upbeat", language: "Hindi" },
  { name: "Kala Chashma", artist: "Amar Arshi, Badshah, Neha Kakkar", category: "Upbeat", language: "Hindi" },
  { name: "Aankh Marey", artist: "Neha Kakkar, Mika Singh", category: "Upbeat", language: "Hindi" },
  { name: "Kamariya", artist: "Lijo George, DJ Chetas", category: "Upbeat", language: "Hindi" },
  { name: "Sweety Tera Drama", artist: "Dev Negi, Pawni Pandey", category: "Upbeat", language: "Hindi" },
  { name: "Dil Chori", artist: "Yo Yo Honey Singh, Simar Kaur", category: "Upbeat", language: "Hindi" },
  { name: "Kar Gayi Chull", artist: "Badshah, Fazilpuria", category: "Upbeat", language: "Hindi" },
  { name: "Nashe Si Chadh Gayi", artist: "Arijit Singh", category: "Upbeat", language: "Hindi" },
  { name: "Chogada", artist: "Darshan Raval", category: "Upbeat", language: "Hindi" },
  { name: "Sau Aasmaan", artist: "Armaan Malik, Neeti Mohan", category: "Chill", language: "Hindi" },
  { name: "Dilbaro", artist: "Harshdeep Kaur, Shankar Mahadevan", category: "Emotional", language: "Hindi" },
  { name: "Duniyaa", artist: "Akhil, Dhvani Bhanushali", category: "Romantic", language: "Hindi" },
  { name: "Photo", artist: "Karan Sehmbi", category: "Romantic", language: "Hindi" },
  { name: "Ve Maahi", artist: "Arijit Singh, Asees Kaur", category: "Romantic", language: "Hindi" },
  { name: "Main Hoon Hero Tera", artist: "Salman Khan", category: "Romantic", language: "Hindi" },
  { name: "Humnava Mere", artist: "Jubin Nautiyal", category: "Sad", language: "Hindi" },
  { name: "Pal Pal Dil Ke Paas", artist: "Arijit Singh, Parampara Thakur", category: "Romantic", language: "Hindi" },
  { name: "Mere Sohneya", artist: "Sachet Tandon, Parampara Thakur", category: "Romantic", language: "Hindi" },
  { name: "Mehrama", artist: "Darshan Raval, Antara Mitra", category: "Sad", language: "Hindi" },

  // Add more unique songs up to 200 entries as needed, following the above format:
  // { name: "Song Name", artist: "Artist Name", category: "Mood", language: "English" or "Hindi" },
];

export default function SeedSongs() {
  useEffect(() => {
    addSongsListToDatabase(SONGS)
      .then(() => {
        alert("Seeding complete!");
      })
      .catch(() => {
        alert("Seeding failed, see console.");
      });
  }, []);
  return <div>Seeding songs... Check your console for the result.</div>;
}
