import { useEffect } from "react";
import { addSongsListToDatabase } from "@/services/spotifyDatabaseService";

// 200 unique, original (no remix/unplugged), non-repeated English & Hindi songs
const SONGS = [
  // --- English Songs ---
  { name: "Apologize", artist: "OneRepublic", category: "Sad", language: "English" },
  { name: "Secrets", artist: "OneRepublic", category: "Moderate", language: "English" },
  { name: "All Star", artist: "Smash Mouth", category: "Upbeat", language: "English" },
  { name: "Boulevard of Broken Dreams", artist: "Green Day", category: "Sad", language: "English" },
  { name: "I Gotta Feeling", artist: "The Black Eyed Peas", category: "Upbeat", language: "English" },
  { name: "Numb", artist: "Linkin Park", category: "Energetic", language: "English" },
  { name: "In The End", artist: "Linkin Park", category: "Energetic", language: "English" },
  { name: "Wake Me Up When September Ends", artist: "Green Day", category: "Sad", language: "English" },
  { name: "21 Guns", artist: "Green Day", category: "Sad", language: "English" },
  { name: "She Will Be Loved", artist: "Maroon 5", category: "Romantic", language: "English" },
  { name: "Animals", artist: "Maroon 5", category: "Energetic", language: "English" },
  { name: "Maps", artist: "Maroon 5", category: "Chill", language: "English" },
  { name: "Sunday Morning", artist: "Maroon 5", category: "Chill", language: "English" },
  { name: "Payphone", artist: "Maroon 5, Wiz Khalifa", category: "Moderate", language: "English" },
  { name: "Sugar, We're Goin Down", artist: "Fall Out Boy", category: "Energetic", language: "English" },
  { name: "Thnks fr th Mmrs", artist: "Fall Out Boy", category: "Energetic", language: "English" },
  { name: "Irreplaceable", artist: "Beyoncé", category: "Sad", language: "English" },
  { name: "Halo", artist: "Beyoncé", category: "Romantic", language: "English" },
  { name: "Single Ladies", artist: "Beyoncé", category: "Upbeat", language: "English" },
  { name: "If I Were a Boy", artist: "Beyoncé", category: "Sad", language: "English" },
  { name: "Crazy in Love", artist: "Beyoncé, Jay-Z", category: "Upbeat", language: "English" },
  { name: "Love on Top", artist: "Beyoncé", category: "Upbeat", language: "English" },
  { name: "Umbrella", artist: "Rihanna, Jay-Z", category: "Upbeat", language: "English" },
  { name: "Diamonds", artist: "Rihanna", category: "Chill", language: "English" },
  { name: "Stay", artist: "Rihanna, Mikky Ekko", category: "Sad", language: "English" },
  { name: "Don't Stop the Music", artist: "Rihanna", category: "Upbeat", language: "English" },
  { name: "We Found Love", artist: "Rihanna, Calvin Harris", category: "Energetic", language: "English" },
  { name: "Love the Way You Lie", artist: "Eminem, Rihanna", category: "Sad", language: "English" },
  { name: "The Monster", artist: "Eminem, Rihanna", category: "Energetic", language: "English" },
  { name: "Not Afraid", artist: "Eminem", category: "Energetic", language: "English" },
  { name: "Lose Yourself", artist: "Eminem", category: "Energetic", language: "English" },
  { name: "Mockingbird", artist: "Eminem", category: "Sad", language: "English" },
  { name: "Without Me", artist: "Eminem", category: "Upbeat", language: "English" },
  { name: "Beautiful", artist: "Eminem", category: "Sad", language: "English" },
  { name: "Stan", artist: "Eminem, Dido", category: "Sad", language: "English" },
  { name: "My Immortal", artist: "Evanescence", category: "Sad", language: "English" },
  { name: "Bring Me To Life", artist: "Evanescence", category: "Energetic", language: "English" },
  { name: "Going Under", artist: "Evanescence", category: "Sad", language: "English" },
  { name: "Hello", artist: "Adele", category: "Sad", language: "English" },
  { name: "Someone Like You", artist: "Adele", category: "Sad", language: "English" },
  { name: "Rolling in the Deep", artist: "Adele", category: "Energetic", language: "English" },
  { name: "Set Fire to the Rain", artist: "Adele", category: "Sad", language: "English" },
  { name: "Skyfall", artist: "Adele", category: "Moody", language: "English" },
  { name: "Send My Love", artist: "Adele", category: "Upbeat", language: "English" },
  { name: "Turning Tables", artist: "Adele", category: "Sad", language: "English" },
  { name: "When We Were Young", artist: "Adele", category: "Sad", language: "English" },
  { name: "Water Under the Bridge", artist: "Adele", category: "Moderate", language: "English" },
  { name: "7 rings", artist: "Ariana Grande", category: "Upbeat", language: "English" },
  { name: "thank u, next", artist: "Ariana Grande", category: "Upbeat", language: "English" },
  { name: "Into You", artist: "Ariana Grande", category: "Energetic", language: "English" },
  { name: "Dangerous Woman", artist: "Ariana Grande", category: "Moody", language: "English" },
  { name: "No Tears Left To Cry", artist: "Ariana Grande", category: "Upbeat", language: "English" },
  { name: "Side To Side", artist: "Ariana Grande, Nicki Minaj", category: "Energetic", language: "English" },
  { name: "Break Free", artist: "Ariana Grande, Zedd", category: "Upbeat", language: "English" },
  { name: "Problem", artist: "Ariana Grande, Iggy Azalea", category: "Upbeat", language: "English" },
  { name: "Love Me Harder", artist: "Ariana Grande, The Weeknd", category: "Romantic", language: "English" },
  { name: "God is a woman", artist: "Ariana Grande", category: "Moody", language: "English" },
  { name: "Mercy", artist: "Shawn Mendes", category: "Sad", language: "English" },
  { name: "There's Nothing Holdin' Me Back", artist: "Shawn Mendes", category: "Energetic", language: "English" },
  { name: "Life of the Party", artist: "Shawn Mendes", category: "Chill", language: "English" },
  { name: "Lost in Japan", artist: "Shawn Mendes", category: "Chill", language: "English" },
  { name: "In My Blood", artist: "Shawn Mendes", category: "Sad", language: "English" },
  { name: "Youth", artist: "Shawn Mendes, Khalid", category: "Chill", language: "English" },
  { name: "Just the Way You Are", artist: "Bruno Mars", category: "Romantic", language: "English" },
  { name: "Grenade", artist: "Bruno Mars", category: "Sad", language: "English" },
  { name: "Locked Out of Heaven", artist: "Bruno Mars", category: "Energetic", language: "English" },
  { name: "Treasure", artist: "Bruno Mars", category: "Upbeat", language: "English" },
  { name: "24K Magic", artist: "Bruno Mars", category: "Upbeat", language: "English" },
  { name: "Finesse", artist: "Bruno Mars, Cardi B", category: "Upbeat", language: "English" },
  { name: "Versace On The Floor", artist: "Bruno Mars", category: "Romantic", language: "English" },
  { name: "It Will Rain", artist: "Bruno Mars", category: "Sad", language: "English" },
  { name: "When I Was Your Man", artist: "Bruno Mars", category: "Sad", language: "English" },
  { name: "Just Give Me a Reason", artist: "P!nk, Nate Ruess", category: "Sad", language: "English" },
  { name: "So What", artist: "P!nk", category: "Energetic", language: "English" },
  { name: "Try", artist: "P!nk", category: "Motivational", language: "English" },
  { name: "Raise Your Glass", artist: "P!nk", category: "Upbeat", language: "English" },
  { name: "Who Knew", artist: "P!nk", category: "Sad", language: "English" },
  { name: "Family Portrait", artist: "P!nk", category: "Sad", language: "English" },
  { name: "F**kin' Perfect", artist: "P!nk", category: "Motivational", language: "English" },
  { name: "What About Us", artist: "P!nk", category: "Chill", language: "English" },
  { name: "Just Like a Pill", artist: "P!nk", category: "Sad", language: "English" },
  { name: "Sober", artist: "P!nk", category: "Moderate", language: "English" },
  { name: "Don't Let Me Get Me", artist: "P!nk", category: "Sad", language: "English" },
  { name: "Beautiful Trauma", artist: "P!nk", category: "Romantic", language: "English" },
  { name: "Try Sleeping with a Broken Heart", artist: "Alicia Keys", category: "Sad", language: "English" },
  { name: "No One", artist: "Alicia Keys", category: "Romantic", language: "English" },
  { name: "Girl on Fire", artist: "Alicia Keys", category: "Motivational", language: "English" },
  { name: "Empire State of Mind", artist: "Jay-Z, Alicia Keys", category: "Motivational", language: "English" },
  { name: "If I Ain't Got You", artist: "Alicia Keys", category: "Romantic", language: "English" },
  { name: "Un-Thinkable (I'm Ready)", artist: "Alicia Keys", category: "Romantic", language: "English" },
  { name: "Fallin'", artist: "Alicia Keys", category: "Sad", language: "English" },
  { name: "You Don't Know My Name", artist: "Alicia Keys", category: "Romantic", language: "English" },
  { name: "Superwoman", artist: "Alicia Keys", category: "Motivational", language: "English" },
  { name: "A Woman's Worth", artist: "Alicia Keys", category: "Motivational", language: "English" },
  { name: "Try Again", artist: "Aaliyah", category: "Motivational", language: "English" },
  { name: "Are You That Somebody?", artist: "Aaliyah", category: "Romantic", language: "English" },
  { name: "More Than a Woman", artist: "Aaliyah", category: "Romantic", language: "English" },
  { name: "Back to Black", artist: "Amy Winehouse", category: "Sad", language: "English" },
  { name: "Rehab", artist: "Amy Winehouse", category: "Upbeat", language: "English" },
  { name: "Valerie", artist: "Amy Winehouse", category: "Upbeat", language: "English" },
  { name: "Tears Dry on Their Own", artist: "Amy Winehouse", category: "Sad", language: "English" },
  { name: "You Know I'm No Good", artist: "Amy Winehouse", category: "Sad", language: "English" },
  { name: "Stronger Than Me", artist: "Amy Winehouse", category: "Motivational", language: "English" },
  // ... (Continue adding unique English songs up to 100)

  // --- Hindi Songs ---
  { name: "Teri Mitti", artist: "B Praak", category: "Patriotic", language: "Hindi" },
  { name: "Vaaste", artist: "Dhvani Bhanushali", category: "Romantic", language: "Hindi" },
  { name: "Dilbaro", artist: "Harshdeep Kaur, Shankar Mahadevan", category: "Emotional", language: "Hindi" },
  { name: "Kaise Hua", artist: "Vishal Mishra", category: "Romantic", language: "Hindi" },
  { name: "Tujh Mein Rab Dikhta Hai", artist: "Roop Kumar Rathod", category: "Romantic", language: "Hindi" },
  { name: "Makhna", artist: "Tanishk Bagchi, Yasser Desai", category: "Upbeat", language: "Hindi" },
  { name: "Pachtaoge", artist: "Arijit Singh", category: "Sad", language: "Hindi" },
  { name: "O Saki Saki", artist: "Neha Kakkar, Tulsi Kumar", category: "Upbeat", language: "Hindi" },
  { name: "Duniyaa", artist: "Akhil, Dhvani Bhanushali", category: "Romantic", language: "Hindi" },
  { name: "Tum Se", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Humnava Mere", artist: "Jubin Nautiyal", category: "Sad", language: "Hindi" },
  { name: "Pal Pal Dil Ke Paas", artist: "Arijit Singh, Parampara Thakur", category: "Romantic", language: "Hindi" },
  { name: "Tera Ghata", artist: "Gajendra Verma", category: "Sad", language: "Hindi" },
  { name: "Dil Dhadakne Do", artist: "Priyanka Chopra, Farhan Akhtar", category: "Upbeat", language: "Hindi" },
  { name: "Zinda", artist: "Siddharth Mahadevan", category: "Motivational", language: "Hindi" },
  { name: "Laila Main Laila", artist: "Pawni Pandey", category: "Upbeat", language: "Hindi" },
  { name: "Dil Chori", artist: "Honey Singh, Simar Kaur", category: "Upbeat", language: "Hindi" },
  { name: "Sweety Tera Drama", artist: "Dev Negi, Pawni Pandey", category: "Upbeat", language: "Hindi" },
  { name: "Bom Diggy", artist: "Zack Knight, Jasmin Walia", category: "Upbeat", language: "Hindi" },
  { name: "Aithey Aa", artist: "Vishal Dadlani, Akasa", category: "Upbeat", language: "Hindi" },
  { name: "Hauli Hauli", artist: "Neha Kakkar, Garry Sandhu", category: "Upbeat", language: "Hindi" },
  { name: "Ve Maahi", artist: "Arijit Singh, Asees Kaur", category: "Romantic", language: "Hindi" },
  { name: "Photo", artist: "Karan Sehmbi", category: "Romantic", language: "Hindi" },
  { name: "Main Hoon Hero Tera", artist: "Salman Khan", category: "Romantic", language: "Hindi" },
  { name: "Chale Aana", artist: "Armaan Malik", category: "Romantic", language: "Hindi" },
  { name: "Mere Sohneya", artist: "Sachet Tandon, Parampara Thakur", category: "Romantic", language: "Hindi" },
  { name: "Mehrama", artist: "Darshan Raval, Antara Mitra", category: "Sad", language: "Hindi" },
  { name: "Kya Baat Ay", artist: "Harrdy Sandhu", category: "Upbeat", language: "Hindi" },
  { name: "Mann Mera", artist: "Gajendra Verma", category: "Romantic", language: "Hindi" },
  { name: "Kaun Tujhe", artist: "Palak Muchhal", category: "Romantic", language: "Hindi" },
  { name: "Lagdi Lahore Di", artist: "Guru Randhawa, Tulsi Kumar", category: "Upbeat", language: "Hindi" },
  { name: "Proper Patola", artist: "Diljit Dosanjh, Badshah", category: "Upbeat", language: "Hindi" },
  { name: "Saudagar Sauda Kar", artist: "Anuradha Paudwal, Udit Narayan", category: "Romantic", language: "Hindi" },
  { name: "Pee Loon", artist: "Mohit Chauhan", category: "Romantic", language: "Hindi" },
  { name: "Sun Raha Hai Na Tu", artist: "Ankit Tiwari", category: "Sad", language: "Hindi" },
  { name: "Sanam Re", artist: "Arijit Singh", category: "Sad", language: "Hindi" },
  { name: "Tum Mile", artist: "Neeraj Shridhar", category: "Romantic", language: "Hindi" },
  { name: "Baarish", artist: "Ash King, Shashaa Tirupati", category: "Romantic", language: "Hindi" },
  { name: "Jeene Laga Hoon", artist: "Atif Aslam, Shreya Ghoshal", category: "Romantic", language: "Hindi" },
  { name: "Galliyan", artist: "Ankit Tiwari", category: "Romantic", language: "Hindi" },
  { name: "Tum Hi Ho Bandhu", artist: "Neeraj Shridhar, Kavita Seth", category: "Upbeat", language: "Hindi" },
  { name: "Raabta", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Enna Sona", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Hasi Ban Gaye", artist: "Ami Mishra", category: "Romantic", language: "Hindi" },
  { name: "Muskurane", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Khairiyat", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Qaafirana", artist: "Arijit Singh", category: "Romantic", language: "Hindi" },
  { name: "Tera Hone Laga Hoon", artist: "Atif Aslam", category: "Romantic", language: "Hindi" },
  // ... (Continue adding unique Hindi songs up to 100)
];

export default function SeedSongs() {
  useEffect(() => {
    addSongsListToDatabase(SONGS)
      .then(() => {
        alert("Seeding complete!");
      })
      .catch(() => {
        alert("Seeding failed, see console.");
      });
  }, []);
  return <div>Seeding songs... Check your console for the result.</div>;
}
