
import { Song, SongCategory } from './fuzzyLogic';

export const additionalSongs: Song[] = [
  {
    id: "add_1",
    title: "Tum Hi Ho",
    artist: "Arijit Singh",
    album: "Aashiqui 2",
    language: "Hindi",
    category: SongCategory.CALM,
    energy: 0.3,
    valence: 0.6,
    danceability: 0.4,
    coverImage: "https://c.saavncdn.com/314/Aashiqui-2-Hindi-2013-20190607040147-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/4PSYY1pwpHLyWn48EgIlQi",
    tags: ["romantic", "bollywood", "emotional"]
  },
  {
    id: "add_2",
    title: "Channa Mereya",
    artist: "Arijit Singh",
    album: "Ae Dil Hai Mushkil",
    language: "Hindi",
    category: SongCategory.CALM,
    energy: 0.4,
    valence: 0.3,
    danceability: 0.3,
    coverImage: "https://c.saavncdn.com/191/Ae-Dil-Hai-Mushkil-Hindi-2016-20210127135942-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/1HNkqx9Ahdgi1Ixy2xkKkL",
    tags: ["emotional", "bollywood", "heartbreak"]
  },
  {
    id: "add_3",
    title: "Raabta",
    artist: "Arijit Singh",
    album: "Agent Vinod",
    language: "Hindi",
    category: SongCategory.CALM,
    energy: 0.5,
    valence: 0.7,
    danceability: 0.4,
    coverImage: "https://c.saavncdn.com/506/Agent-Vinod-Hindi-2012-20191021084442-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/6H6WHTlRdC1E4UZmSTy9ov",
    tags: ["romantic", "bollywood", "soulful"]
  },
  {
    id: "add_4",
    title: "Dil Diyan Gallan",
    artist: "Atif Aslam",
    album: "Tiger Zinda Hai",
    language: "Hindi",
    category: SongCategory.RELAXED,
    energy: 0.6,
    valence: 0.8,
    danceability: 0.5,
    coverImage: "https://c.saavncdn.com/421/Tiger-Zinda-Hai-Hindi-2017-20171201090000-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/0qCTOxvdGsQaVLh8IyoAG4",
    tags: ["romantic", "bollywood", "uplifting"]
  },
  {
    id: "add_5",
    title: "Kesariya",
    artist: "Arijit Singh",
    album: "Brahmastra",
    language: "Hindi",
    category: SongCategory.RELAXED,
    energy: 0.7,
    valence: 0.7,
    danceability: 0.6,
    coverImage: "https://c.saavncdn.com/398/Brahmastra-Hindi-2022-20220831110838-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/5MYHcaCDIfElFckgGBbrFF",
    tags: ["romantic", "bollywood", "melodic"]
  },
  {
    id: "add_6",
    title: "Bekhayali",
    artist: "Sachet Tandon",
    album: "Kabir Singh",
    language: "Hindi",
    category: SongCategory.MODERATE,
    energy: 0.5,
    valence: 0.4,
    danceability: 0.4,
    coverImage: "https://c.saavncdn.com/652/Kabir-Singh-Hindi-2019-20190620102531-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/3ySK0gkw63TT5TqxkQN5Si",
    tags: ["emotional", "bollywood", "heartbreak"]
  },
  {
    id: "add_7",
    title: "Phir Bhi Tumko Chaahunga",
    artist: "Arijit Singh",
    album: "Half Girlfriend",
    language: "Hindi",
    category: SongCategory.MODERATE,
    energy: 0.6,
    valence: 0.5,
    danceability: 0.5,
    coverImage: "https://c.saavncdn.com/068/Half-Girlfriend-Hindi-2017-20170428180000-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/4P8sKq4MjHBU9p7NfKXrUP",
    tags: ["romantic", "bollywood", "passionate"]
  },
  {
    id: "add_8",
    title: "Galway Girl",
    artist: "Ed Sheeran",
    album: "÷ (Divide)",
    language: "English",
    category: SongCategory.UPBEAT,
    energy: 0.8,
    valence: 0.8,
    danceability: 0.7,
    coverImage: "https://i.scdn.co/image/ab67616d0000b273ba5db46f4b838ef6027e6f96",
    spotifyUrl: "https://open.spotify.com/track/6Mi7RrMgUTzAZBHIkB0tJ5",
    tags: ["pop", "upbeat", "folk"]
  },
  {
    id: "add_9",
    title: "Can't Stop the Feeling!",
    artist: "Justin Timberlake",
    album: "Trolls (Original Motion Picture Soundtrack)",
    language: "English",
    category: SongCategory.UPBEAT,
    energy: 0.9,
    valence: 0.9,
    danceability: 0.8,
    coverImage: "https://i.scdn.co/image/ab67616d0000b273aa9ca3c7e6ec7ecf9a98a494",
    spotifyUrl: "https://open.spotify.com/track/6NPVjNh8Jhru9xOmyQigds",
    tags: ["pop", "happy", "dance"]
  },
  {
    id: "add_10",
    title: "Pumped Up Kicks",
    artist: "Foster the People",
    album: "Torches",
    language: "English",
    category: SongCategory.ENERGETIC,
    energy: 0.8,
    valence: 0.7,
    danceability: 0.8,
    coverImage: "https://i.scdn.co/image/ab67616d0000b273c5649add07ed3720be9d5526",
    spotifyUrl: "https://open.spotify.com/track/7w87IxuO7BDcJ3YUqCyMTT",
    tags: ["indie", "alternative", "electronic"]
  },
  {
    id: "add_11",
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    album: "Uptown Special",
    language: "English",
    category: SongCategory.ENERGETIC,
    energy: 0.9,
    valence: 0.9,
    danceability: 0.9,
    coverImage: "https://i.scdn.co/image/ab67616d0000b273b4823eb0a34bc6cec5b9e88e",
    spotifyUrl: "https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS",
    tags: ["funk", "dance", "retro"]
  },
  {
    id: "add_12",
    title: "Tera Ban Jaunga",
    artist: "Tulsi Kumar, Akhil Sachdeva",
    album: "Kabir Singh",
    language: "Hindi",
    category: SongCategory.CALM,
    energy: 0.4,
    valence: 0.6,
    danceability: 0.3,
    coverImage: "https://c.saavncdn.com/652/Kabir-Singh-Hindi-2019-20190620102531-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/5yk7B4hWEuMdRE3FGVd1c7",
    tags: ["romantic", "bollywood", "melodic"]
  },
  {
    id: "add_13",
    title: "Hawayein",
    artist: "Arijit Singh",
    album: "Jab Harry Met Sejal",
    language: "Hindi",
    category: SongCategory.CALM,
    energy: 0.5,
    valence: 0.7,
    danceability: 0.4,
    coverImage: "https://c.saavncdn.com/405/Jab-Harry-Met-Sejal-Hindi-2017-20170728181500-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/77k4M0gQE0T1oI1XZzKPDC",
    tags: ["romantic", "bollywood", "soothing"]
  },
  {
    id: "add_14",
    title: "Dil Ko Karaar Aaya",
    artist: "Neha Kakkar, Yasser Desai",
    album: "Sidharth Shukla Music Video",
    language: "Hindi",
    category: SongCategory.RELAXED,
    energy: 0.6,
    valence: 0.8,
    danceability: 0.6,
    coverImage: "https://c.saavncdn.com/217/Dil-Ko-Karaar-Aaya-Hindi-2020-20200911021127-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/4VGhq6TjQ1WwVfP8hzJUhF",
    tags: ["romantic", "bollywood", "contemporary"]
  },
  {
    id: "add_15",
    title: "Kaise Hua",
    artist: "Vishal Mishra",
    album: "Kabir Singh",
    language: "Hindi",
    category: SongCategory.RELAXED,
    energy: 0.5,
    valence: 0.7,
    danceability: 0.4,
    coverImage: "https://c.saavncdn.com/652/Kabir-Singh-Hindi-2019-20190620102531-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/70iHjGQhq7KnyEKj3FJqgH",
    tags: ["romantic", "bollywood", "emotional"]
  },
  {
    id: "add_16",
    title: "Apna Time Aayega",
    artist: "Ranveer Singh",
    album: "Gully Boy",
    language: "Hindi",
    category: SongCategory.MODERATE,
    energy: 0.8,
    valence: 0.8,
    danceability: 0.7,
    coverImage: "https://c.saavncdn.com/313/Gully-Boy-Hindi-2019-20190211180857-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/6rPO02ozF3bM7NnOV4h6s2",
    tags: ["hip-hop", "motivational", "bollywood"]
  },
  {
    id: "add_17",
    title: "Malang Sajna",
    artist: "Sachet Tandon",
    album: "Malang",
    language: "Hindi",
    category: SongCategory.MODERATE,
    energy: 0.7,
    valence: 0.6,
    danceability: 0.6,
    coverImage: "https://c.saavncdn.com/037/Malang-Hindi-2020-20200203081528-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/0YLhBYtqHm5vEsJVGm0FjW",
    tags: ["romantic", "bollywood", "contemporary"]
  },
  {
    id: "add_18",
    title: "Naach Meri Rani",
    artist: "Guru Randhawa, Nora Fatehi",
    album: "Single",
    language: "Hindi",
    category: SongCategory.UPBEAT,
    energy: 0.9,
    valence: 0.8,
    danceability: 0.9,
    coverImage: "https://c.saavncdn.com/395/Naach-Meri-Rani-Hindi-2020-20201021030401-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/5YKAINwCIb6b8oZJYs7K6m",
    tags: ["dance", "punjabi", "party"]
  },
  {
    id: "add_19",
    title: "Burj Khalifa",
    artist: "Shashi, DJ Khushi",
    album: "Laxmii",
    language: "Hindi",
    category: SongCategory.UPBEAT,
    energy: 0.9,
    valence: 0.9,
    danceability: 0.9,
    coverImage: "https://c.saavncdn.com/037/Laxmii-Hindi-2020-20201105151538-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/2EI7YOTjWAaHWpJZMGYPRQ",
    tags: ["dance", "bollywood", "party"]
  },
  {
    id: "add_20",
    title: "Kar Gayi Chull",
    artist: "Neha Kakkar, Badshah",
    album: "Kapoor & Sons",
    language: "Hindi",
    category: SongCategory.ENERGETIC,
    energy: 0.95,
    valence: 0.9,
    danceability: 0.95,
    coverImage: "https://c.saavncdn.com/242/Kapoor-Sons-Since-1921--Hindi-2016-20190607034842-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/65FftemJ1DbbCEBuKlb7XG",
    tags: ["dance", "bollywood", "party"]
  },
  {
    id: "add_21",
    title: "Garmi",
    artist: "Neha Kakkar, Badshah",
    album: "Street Dancer 3D",
    language: "Hindi",
    category: SongCategory.ENERGETIC,
    energy: 0.95,
    valence: 0.85,
    danceability: 0.95,
    coverImage: "https://c.saavncdn.com/037/Street-Dancer-3D-Hindi-2020-20200124064139-500x500.jpg",
    spotifyUrl: "https://open.spotify.com/track/0tc5vWNY37OJRNdkM5XzkV",
    tags: ["dance", "bollywood", "energetic"]
  },
  {
    id: "add_22",
    title: "Perfect",
    artist: "Ed Sheeran",
    album: "÷ (Divide)",
    language: "English",
    category: SongCategory.CALM,
    energy: 0.4,
    valence: 0.8,
    danceability: 0.3,
    coverImage: "https://i.scdn.co/image/ab67616d0000b273ba5db46f4b838ef6027e6f96",
    spotifyUrl: "https://open.spotify.com/track/0tgVpDi06FyKpA1z0VMD4v",
    tags: ["romantic", "pop", "acoustic"]
  },
  {
    id: "add_23",
    title: "Someone Like You",
    artist: "Adele",
    album: "21",
    language: "English",
    category: SongCategory.RELAXED,
    energy: 0.3,
    valence: 0.4,
    danceability: 0.3,
    coverImage: "https://i.scdn.co/image/ab67616d0000b2732118bf9b198b05a95ded6300",
    spotifyUrl: "https://open.spotify.com/track/1zwMYTA5nlNjZxYrvBB2pV",
    tags: ["emotional", "soul", "ballad"]
  },
  {
    id: "add_24",
    title: "Counting Stars",
    artist: "OneRepublic",
    album: "Native",
    language: "English",
    category: SongCategory.MODERATE,
    energy: 0.7,
    valence: 0.7,
    danceability: 0.6,
    coverImage: "https://i.scdn.co/image/ab67616d0000b273c8b444df094279e70d0ed856",
    spotifyUrl: "https://open.spotify.com/track/2tpWsVSb9UEmDRxAl1zhX1",
    tags: ["pop-rock", "uplifting", "anthemic"]
  },
  {
    id: "add_25",
    title: "Shut Up and Dance",
    artist: "Walk the Moon",
    album: "Talking Is Hard",
    language: "English",
    category: SongCategory.UPBEAT,
    energy: 0.9,
    valence: 0.9,
    danceability: 0.8,
    coverImage: "https://i.scdn.co/image/ab67616d0000b273d136b4506dfd3671b895d72b",
    spotifyUrl: "https://open.spotify.com/track/4kbj7SPAHsHBeSm8jy9vP3",
    tags: ["indie-pop", "dance", "feel-good"]
  },
  {
    id: "add_26",
    title: "Thunder",
    artist: "Imagine Dragons",
    album: "Evolve",
    language: "English",
    category: SongCategory.ENERGETIC,
    energy: 0.8,
    valence: 0.8,
    danceability: 0.7,
    coverImage: "https://i.scdn.co/image/ab67616d0000b273408fb80aa5b1b8752c95bf80",
    spotifyUrl: "https://open.spotify.com/track/1zB4vmk8tFRmM9UULNzbLB",
    tags: ["pop-rock", "electronic", "anthemic"]
  }
];
