// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqtdyfzxzatzymyfitqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxdGR5Znp4emF0enlteWZpdHFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzYxMTUsImV4cCI6MjA2NDgxMjExNX0.MBjP7fVH87XUle2zTQJ3Wnp2NjGxKUM2Re5gsI60JH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);